spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:http://localhost:1000"
  application:
    name: gateway-service
---
spring:
  config:
    import: "optional:configserver:http://configuration-service:1000"
    activate:
      on-profile: docker